### ISSUE TITLE
Robust compiler settings

### ISSUE THREAD

**Issue by wlandau** [wlandau/instantiate#1]
Every compilation in `instantiate` happens inside `install.packages()`, which messes with compiler settings like `CXXFLAGS`. https://github.com/stan-dev/cmdstanr/issues/787 is just one instance of this. It would be great to reliably configure the toolchain.

**Comment by wlandau** [comment]
@jgabry, are there environment variables I can set up front in a platform-independent way to ensure Stan models compile inside `install.packages()` the same way they would ordinarily compile outside package installation?

**Comment by jgabry** [comment]
To be honest, I'm not sure I fully understand why there's currently a difference inside vs outside `install.packages`.  @rok-cesnovar @andrjohns any thoughts on CmdStan environment variables that could help here?

**Comment by andrjohns** [comment]
Try using `withr::with_makevars()` to control the makeflags being used ([example here](https://github.com/stan-dev/cmdstanr/blob/master/R/utils.R#L732))

**Comment by wlandau** [comment]
`with_makevars()` could definitely help with [`stan_package_compile()`](https://github.com/wlandau/instantiate/blob/main/R/stan_package_compile.R) and [internal CmdStan installation](https://github.com/wlandau/instantiate/blob/main/inst/cmdstan.R) if I know what environment variables to set and the values to supply. Is there a safe/universal configuration I can use? I see the `with_makevars()` call you shared sets `USE_CXX14 = 1`, `PKG_CPPFLAGS = ""` for sufficiently recent CmdStan, and some custom stuff for `PKG_CXXFLAGS` and `PKG_LIBS`. Are those the only envvars I would need? Would it be reasonable to emulate `rcpp_source_stan()` and `get_cmdstan_flags()`?
